FSWeb/Models/CategoryUI.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FSWeb.Models
{
    public class CategoryUI
    {
        public int Id { get; set; }
        public String Name { get; set; }
    }
}

FSWeb/Models/ItemUI.cs
using System;
using FSWeb.Data.Models;

namespace FSWeb.Models
{
    public class ItemUI
    {
        public int Id { get; set; }
        public String Name { get; set; }
        public String Notes { get; set; }
        public int CategoryId { get; set; }

        public override string ToString()
        {
            return String.Format("Id - {0} ; Name - {1} ; Notes - {2} ; CategoryId - {3}", Id, Name, Notes, CategoryId);
        }
    }
}

FSWeb/Models/ViewModels/HomeIndexVM.cs
using System;
using System.Collections.Generic;

namespace FSWeb.Models.ViewModels
{
    public class HomeIndexVM
    {
        public PagingInfo PagingInfo { get; set; }
        public IEnumerable<ItemSummaryVM> ItemSummaries { get; set; }
        public String CurrentCategory { get; set; }

    }
}

FSWeb/Models/ViewModels/HomeIndexViewModel.cs
using FSWeb.Data.Models;
using FSWeb.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FSWeb.Models.ViewModels
{
    public class HomeIndexViewModel
    {
        public PagingInfo PagingInfo { get; set; }
        public IEnumerable<ItemSummaryVM> ItemSummaries { get; set; }
        public String CurrentCategory { get; set; }

    }
}

FSWeb/Models/ViewModels/ItemSummaryVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FSWeb.Models.ViewModels
{
    public class ItemSummaryVM
    {
        public ItemSummaryVM() { }

        public ItemSummaryVM(String catName, int catId, String itemName, int itemId, int findCount, DateTime lastFind)
        {
            CategoryName = catName;
            CategoryId = catId;
            ItemName = itemName;
            ItemId = itemId;
            FindCount = findCount;
            LastFind = lastFind;
        }

        public String CategoryName { get; set; }
        public int CategoryId { get; set;  }
        public String ItemName { get; set;  }
        public int ItemId { get; set; }
        public int FindCount { get; set; }
        public DateTime LastFind { get; set;  }
        public override string ToString()
        {
            return String.Format("CategoryName - {0} ; CategoryId - {1} ; ItemName - {2} ; ItemId - {3} ; FindCount - {4} ; LastFind - {5} ", CategoryName, CategoryId, ItemName, ItemId, FindCount, LastFind);

        }
    }
}

FSWeb/Models/ViewModels/ItemVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FSWeb.Models.ViewModels
{
    public class ItemVM
    {
        public ItemUI Item { get; set; }
        public CategoryUI Category { get; set; }
        public List<SelectListItem> CategorySelector { get; set; }
    }
}

FSWeb/Models/ViewModels/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FSWeb.Models.ViewModels
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages => (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
    }
}

FSWeb/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FSWeb.Repository;
using FSWeb.Infrastructure.Routing;

namespace FSWeb.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        IRepository repository;

        public NavigationMenuViewComponent(IRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values[RoutingConstants.Segment.Category.ToLower()];
            // ToDo - This should use Category - not ItemSummary
            return View(repository
                .ItemSummaries
                .Select(itemSummary => itemSummary.CategoryName)
                .Distinct()
                .OrderBy(catName => catName));
        }
    }
}

FSWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FSWeb.Data.Models;
using FSWeb.Models.ViewModels;
using FSWeb.Repository;
using Microsoft.AspNetCore.Mvc;


namespace FSWeb.Controllers
{
    public class HomeController : Controller
    {
        IRepository repository;
        int PageSize = 2;

        public HomeController(IRepository repo)
        {
            repository = repo;
        }
        public IActionResult Index(String category, int page = 1)
        {

            IEnumerable<ItemSummaryVM> isvms = repository.ItemSummaries.Where(itemSum => category == null || itemSum.CategoryName.Equals(category, StringComparison.CurrentCultureIgnoreCase));
            HomeIndexVM vm = new HomeIndexVM()

            {
                ItemSummaries = isvms.OrderBy(i => i.CategoryName)
                .OrderBy(i => i.ItemName)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),

                CurrentCategory = category,

                PagingInfo = new PagingInfo()
                {
                    
                    TotalItems = isvms.Count(),
                    ItemsPerPage = PageSize,
                    CurrentPage = page
                }
            };
            return View(vm);
        }
    }
}

FSWeb/Controllers/ItemController.cs
using System.Linq;
using System.Collections.Generic;
using FSWeb.Models;
using FSWeb.Models.ViewModels;
using FSWeb.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FSWeb.Controllers
{
    public class ItemController : Controller
    {
        IRepository repo;

        public ItemController(IRepository repository)
        {
            repo = repository;
        }

        public IActionResult Display(int id)
        {

            List<SelectListItem> categorySelector = new List<SelectListItem>();
            foreach (CategoryUI cat in repo.GetAllCategories().OrderBy(c => c.Name)) {
                categorySelector.Add(new SelectListItem() { Value = cat.Id.ToString(), Text = cat.Name });
            }
            ItemUI item = repo.GetItem(id);
            CategoryUI category = repo.GetCategory(item.CategoryId);
            ItemVM vm = new ItemVM() { Item = item, Category = category, CategorySelector = categorySelector };
            return View(vm);
        }
    }
}

FSWeb/Views/Home/Index.cshtml
@model HomeIndexVM

<div class="row"></div>
<div class="row panel">
    <div id="categories" class="col-3">
        @await Component.InvokeAsync("NavigationMenu")
    </div>
    <div class="col-xs-8">
        @foreach (ItemSummaryVM itemSummary in @Model.ItemSummaries)
        {
            @Html.Partial("ItemSummary", itemSummary)
        }

        <div page-model="@Model.PagingInfo" page-action="Index" page-classes-enabled="true"
             page-class="btn" page-class-normal="btn-secondary" page-url-category="@Model.CurrentCategory"
             page-class-selected="btn-primary" class="btn-group m-1 pull-right">

        </div>

    </div>
</div>

FSWeb/Views/Item/Display.cshtml
@model ItemVM
@*<form asp-controller="Item" asp-action="Display" method="get">*@
<div class="row">
    <div class="col-1">
        <label>Name:</label>
    </div>
    <div class="col-11">
        <input asp-for="@Model.Item.Name" />
    </div>
</div>
<div class="row">
    <div class="col-1">
        <label>Category:</label>
    </div>
    <div class="col-11">
        <select asp-for="@Model.Item.Id" asp-items="@Model.CategorySelector"></select>
    </div>
</div>
<div class="row">
    <div class="col-1">
        <label>Notes:</label>
    </div>
    <div class="col-11">
        <textarea rows="5" cols="80" asp-for="@Model.Item.Notes"></textarea>
    </div>
</div>
@*</form>*@

FSWeb/Views/Shared/Components/NavigationMenu/Default.cshtml
@model IEnumerable<string>
@using FSWeb.Infrastructure.Routing

<a class="btn btn-block btn-default"
   asp-action="@RoutingConstants.Action.Index"
   asp-controller="@RoutingConstants.Controller.Home"
   asp-route-category=""
   asp-route-page="1">
    @RoutingConstants.Controller.Home
</a>

@foreach (string category in Model)
{
    <a class="btn btn-block btn-default @(category==ViewBag.SelectedCategory ? "btn-primary" : "btn-secondary")"
       asp-action="@RoutingConstants.Action.Index"
       asp-controller="@RoutingConstants.Controller.Home"
       asp-route-category="@category"
       asp-route-page="1">
        @category
    </a>
}

FSWeb/Views/Shared/ItemSummary.cshtml
@model ItemSummaryVM

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            <a class="btn btn-block btn-default btn-primary"
               asp-action="@RoutingConstants.Action.Display"
               asp-controller="@RoutingConstants.Controller.Item"
               asp-route-id="@Model.ItemId">
                @Model.ItemName
            </a>


        </h4>
    </div>
    <div class="card-text p-1 ">
        <small style="margin-right: 10px">Finds <span class="badge badge-primary">@Model.FindCount</span></small>
        <span style="float: right;margin-left: 10px">
            <small>Last - @Model.LastFind.ToString("d") </small>
        </span>
    </div>
</div>

FSWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <title>Forage Storage</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">Forage Storage</a>
    </div>
    @RenderBody()
</body>
</html>